version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - rangerrick
    labels:
      - dependabot
    ignore:
      - dependency-name: webpack
        versions:
          - 5.23.0
          - 5.24.2
          - 5.24.3
          - 5.25.1
          - 5.27.1
          - 5.28.0
          - 5.30.0
          - 5.31.2
      - dependency-name: husky
        versions:
          - 5.0.9
      - dependency-name: "@types/node"
    groups:
      babel-and-eslint:
        patterns:
          - "*babel*"
          - "*eslint*"
      commitlint:
        patterns:
          - "*commitlint*"
      jest:
        patterns:
          - "*jest*"
      typescript:
        patterns:
          - "*typescript*"
      webpack:
        patterns:
          - "*webpack*"
          - "*-loader"
    commit-message:
      prefix: build
      include: scope
